# Generated by Django 4.0.4 on 2022-04-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='analyst',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='owner',
            new_name='user',
        ),
    ]
